export { default as AuthRoute } from "./auth/auth.route"
export { default as MediaRoute }  from "./media/media.route"
export { default as HomeRoute } from "./home/home.router"
export { default as UserRoute } from "./user/user.route"
export { default as TokenRoute } from "./token/token.router"